name: Docker Build (Debian)

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile.debian"
      - ".github/workflows/docker_build_debian.yml"
  schedule:
    - cron: "0 0 * * 6"

env:
  DOCKER_REPOSITORY: abcfy2/node_android

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_tag:
          - latest
          - slim
          - 10
          - 10-slim
          - 12
          - 12-slim
          - 14
          - 14-slim
          - 16
          - 16-slim
    steps:
      - name: Determine if push is needed
        run: |
          echo "GITHUB_EVENT_NAME = ${GITHUB_EVENT_NAME}"
          PUSH=true
          if [ "${GITHUB_EVENT_NAME}" = "schedule" ]; then
            UPSTREAM_VER="$(docker run --rm --pull always node:${{ matrix.node_tag }} sh -c 'echo ${NODE_VERSION}' 2>/dev/null)"
            DOWNSTREAM_VER="$(docker run --rm --pull always ${DOCKER_REPOSITORY}:${{ matrix.node_tag }} sh -c 'echo ${NODE_VERSION}' 2>/dev/null)"
            echo "upstream verion: ${UPSTREAM_VER}"
            echo "downstream version: ${DOWNSTREAM_VER}"
            if [ "${UPSTREAM_VER}" = "${DOWNSTREAM_VER}" ]; then
              PUSH=false
            fi
          fi
          echo "PUSH = ${PUSH}"
          echo "PUSH=${PUSH}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.debian
          build-args: |
            NODE_TAG=${{ matrix.node_tag }}
          tags: ${{ env.DOCKER_REPOSITORY }}:${{ matrix.node_tag }}
