name: Docker Build (Alpine)

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile.alpine"
      - ".github/workflows/docker_build_alpine.yml"
  schedule:
    - cron: "0 0 * * 6"

env:
  DOCKER_REPOSITORY: abcfy2/node_android

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_tag:
          - alpine
          - 10-alpine
          - 12-alpine
          - 14-alpine
          - 16-alpine
          - 18-alpine
        jdk_version:
          - 8
          - 11
    steps:
      - name: Determine if push is needed
        run: |
          echo "GITHUB_EVENT_NAME = ${GITHUB_EVENT_NAME}"
          NODE_TAG="${{ matrix.node_tag }}"
          JDK_VERSION="${{ matrix.jdk_version }}"
          PUSH=true
          if [ "${GITHUB_EVENT_NAME}" = "schedule" ]; then
            UPSTREAM_VER="$(docker run --rm --pull always node:${NODE_TAG} sh -c 'echo ${NODE_VERSION}' 2>/dev/null)"
            DOWNSTREAM_VER="$(docker run --rm --pull always ${DOCKER_REPOSITORY}:${NODE_TAG} sh -c 'echo ${NODE_VERSION}' 2>/dev/null)"
            echo "upstream verion: ${UPSTREAM_VER}"
            echo "downstream version: ${DOWNSTREAM_VER}"
            if [ "${UPSTREAM_VER}" = "${DOWNSTREAM_VER}" ]; then
              PUSH=false
            fi
          fi
          echo "PUSH = ${PUSH}"
          echo "PUSH=${PUSH}" >> $GITHUB_ENV
          TAG="${DOCKER_REPOSITORY}:${NODE_TAG}-java${JDK_VERSION}"
          if [ "x${JDK_VERSION}" = x8 ]; then
            TAG="${DOCKER_REPOSITORY}:${NODE_TAG},${TAG}"
          fi
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          # platforms: linux/amd64,linux/arm64/v8
          push: ${{ env.PUSH }}
          pull: true
          context: .
          file: Dockerfile.alpine
          build-args: |
            NODE_TAG=${{ matrix.node_tag }}
            JDK_VERSION=${{ matrix.jdk_version }}
          tags: ${{ env.TAG }}
