name: Daily update docker images

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  check_and_update:
    name: Check and update docker images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        for branch in $(git ls-remote --heads origin | cut -f2 | sed 's@refs/heads/@@'); do
            git checkout -t origin/"${branch}"
            BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"
            VER="${BRANCH_NAME}"
            NODE_TAG="${BRANCH_NAME}"
            if [ "${VER}" = 'master' ]; then
                VER=latest
                NODE_TAG=alpine
            fi
            docker pull node:${NODE_TAG}
            docker pull abcfy2/node_android:${VER}
            UPSTREAM_VER="$(docker run --rm node:${NODE_TAG} sh -c 'echo ${NODE_VERSION}' 2>/dev/null)"
            DOWNSTREAM_VER="$(docker run --rm abcfy2/node_android:${VER} sh -c 'echo ${NODE_VERSION}' 2>/dev/null)"
            echo "upstream verion: ${UPSTREAM_VER}"
            echo "downstream version: ${DOWNSTREAM_VER}"
            [ "${UPSTREAM_VER}" != "${DOWNSTREAM_VER}" ] && \
                curl -sSkLf -d "{\"source_type\": \"Branch\", \"source_name\": \"${BRANCH_NAME}\", \"build\": true}" -H 'Content-Type: application/json' "${DOCKER_HUB_BUILD_TRIGGER_URL}" || \
              true
        done
        git branch
      env:
        DOCKER_HUB_BUILD_TRIGGER_URL: '${{ secrets.DOCKER_HUB_BUILD_TRIGGER_URL }}'
